### ISSUE TITLE
The repository is bloated with large binary blobs

### ISSUE THREAD

**Issue by lyle-nel** [TheZimbo16/COS-301-TheInevitables#11]
Currently the repository is quite large given the amount of content. This is mostly due to version control of the pdfs and images. I propose we use BFG to clean this up so that the repository is faster to clone and use during the project.

**Comment by lyle-univ** [comment]
Some cleanup was done, but this will be an ongoing effort.

**Comment by lyle-univ** [comment]
Reduced from 200mb to 75mb
